version: 0.1.{build}-{branch}
clone_folder: c:\projects\SBGCore
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
    - dev
  except:
    - gh-pages
skip_branch_with_pr: true
image: Visual Studio 2017
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform:
  - x86
  - x64
configuration: Release
build:
  parallel: true
  verbosity: normal
before_build:
  - appveyor-retry nuget restore
  - set DOCFX_SOURCE_BRANCH_NAME=%APPVEYOR_REPO_BRANCH%
after_build:
  - set
  - 7z a SBGCore_%APPVEYOR_BUILD_VERSION%.%Platform%.zip %APPVEYOR_BUILD_FOLDER%\SBGCore\bin\%Platform%\%Configuration%\*.dll
  - 7z a SBGConfig_%APPVEYOR_BUILD_VERSION%.%Platform%.zip %APPVEYOR_BUILD_FOLDER%\SBGConfig\bin\%Platform%\%Configuration%\*.dll
  - 7z a SBGTimer_%APPVEYOR_BUILD_VERSION%.%Platform%.zip %APPVEYOR_BUILD_FOLDER%\SBGTimer\bin\%Platform%\%Configuration%\*.dll
artifacts:
  - path: SBGCore_$(APPVEYOR_BUILD_VERSION).$(platform).zip
    name: SBGCore_$(APPVEYOR_BUILD_VERSION)-bin-$(platform)
  - path: SBGConfig_$(APPVEYOR_BUILD_VERSION).$(platform).zip
    name: SBGConfig_$(APPVEYOR_BUILD_VERSION)-bin-$(platform)
  - path: SBGTimer_$(APPVEYOR_BUILD_VERSION).$(platform).zip
    name: SBGTimer_$(APPVEYOR_BUILD_VERSION)-bin-$(platform)
deploy:
- provider: BinTray
  username: mitoskalandiel
  api_key:
    secure: 3Oxcm6eqQ4IR2sIrHqFFzB3zyi5EQhiGCYFqTbi69y+aaKBs+4TN3u0YPVT5hRld
  subject: sbg-solutions
  repo: SBGCore
  package: SBGCore_bin
  publish: true
  on:
    branch: master